# adapted from [ williamyeh/ansible:ubuntu14.04-onbuild ]
# "ONBUILD version" because:
# - updates some SSL stuff everytime is used in another image
# - copies . to /tmp/ops

# pull base image
FROM ubuntu:14.04

MAINTAINER HighSkillz <webdev@highskillz.com>

#LABEL \
#  version=
#  description=

RUN \
    echo "===> Adding Ansible's PPA..."  && \
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | tee /etc/apt/sources.list.d/ansible.list           && \
    echo "deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/ansible.list    && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7BB9C367    && \
    DEBIAN_FRONTEND=noninteractive  apt-get    update  && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y install \
          apt-transport-https \
          lsb-release \
    && \
    echo "===> Updating TLS certificates..."         && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
            openssl \
	    ca-certificates \
    && \
    \
    echo "===> Upgrading distribution..."  && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y dist-upgrade && \
    \
    echo "===> Adding Python runtime..."  && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y install  \
            python  python-pip \
            python3 python3-pip \
    && \
    echo "===> Adding usefull packages for devops shell-works..."  && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y install  \
            bash \
            less \
            nano \
            \
            curl \
            wget \
            \
            unzip \
            \
        && \
    echo "===> Configuring Python and PIP..."  && \
    pip3 install --upgrade pip setuptools wheel && \
    rm $(which pip) && \
    pip2 install --upgrade pip setuptools wheel && \
    echo Making sure pip is set to python2 && \
    pip --version | grep "python 2\."  && \
    \
    echo "===> Installing NodeJS..."  && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y install  \
          nodejs \
    && \
    echo "===> Adding GO ..."  && \
    DEBIAN_FRONTEND=noninteractive  apt-get -y install  \
            golang \
    && \
    \
    echo "===> Installing Ansible..."  && \
    DEBIAN_FRONTEND=noninteractive  apt-get install -y ansible  && \
    \
    \
    echo "===> Cleaning up ..."  && \
    apt-get autoremove --purge -y && \
    apt-get clean              -y && \
    rm -rf \
      "${HOME}/.cache" \
      /etc/apt/sources.list.d/ansible.list \
      /var/lib/apt/lists/*  && \
    \
    \
    echo "===> Adding hosts for convenience..."  && \
    mkdir -p /etc/ansible                        && \
    echo 'localhost' > /etc/ansible/hosts


COPY ansible-playbook-wrapper /usr/local/bin/

ONBUILD  RUN  \
              DEBIAN_FRONTEND=noninteractive  apt-get update   && \
              echo "===> Updating TLS certificates..."         && \
              DEBIAN_FRONTEND=noninteractive apt-get install -y openssl ca-certificates

ONBUILD  COPY  .  /tmp/ops
ONBUILD  WORKDIR  /tmp/ops
ONBUILD  RUN  \
              echo "===> Diagnosis: host information..."  && \
              ansible -c local -m setup all

# default command: display Ansible version
CMD [ "ansible-playbook", "--version" ]
