---

path_tf_bin: "/usr/local/bin"

addon_version:
    "provisioner":
      #"ansible":   "0.0.2"           # https://github.com/jonmorehouse/terraform-provisioner-ansible/releases
      "ansible":   "0.0.2-joaocc-005"
      # obsolete... # TBD: replace with https://github.com/ravibhure/terraform-provisioner-ansible

addon_installs:
    git: []
    unarchive:
      - name:   "jonmorehouse"
        src:    "https://github.com/joaocc/jonmorehouse--terraform-provisioner-ansible/releases/download/{{ addon_version.provisioner.ansible }}/terraform-provisioner-ansible_{{ addon_version.provisioner.ansible }}_linux_amd64.tar.gz"
        dest:   "{{ path_tf_bin }}"
        mode:   "a+rx"
    get_url: []

