---
- hosts: localhost
  vars:
    VERSIONS:
        "terraform":         "0.6.15"
        "terraform_ansible": "0.0.2"
  # roles:
  #   - role: migibert.terraform
  #     terraform_version: "{{ VERSIONS.terraform }}"
  tasks:
    #- name: add PPAs
    #  apt_repository:
    #    repo='ppa:...'

    - name: distrib upgrade
      apt:
        upgrade: dist
        install_recommends: no
        dpkg_options: "force-confdef,force-confold"
        update_cache: yes
        cache_valid_time: 14400

    - name: add packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 14400
      with_items:
        - wget
        - unzip
        - bash
        - git

    - name: download Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ VERSIONS.terraform }}/terraform_{{ VERSIONS.terraform }}_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: extract Terraform
      unarchive:
        src:  /tmp/terraform.zip
        dest: /usr/local/bin
        copy: no

    - name: download Ansible provisioner for Terraform
      get_url:
        url: "https://github.com/jonmorehouse/terraform-provisioner-ansible/releases/download/{{ VERSIONS.terraform_ansible }}/terraform-provisioner-ansible"
        dest: "/usr/local/bin"
        mode: "a+rx"

- hosts: localhost
  tasks:
    #- apt:
    #    autoremove: yes
    #    purge: yes
    - command: apt-get autoremove --purge -y
    - command: apt-get autoclean -y
    - command: apt-get clean
    - name: "final cleanup"
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/tmp/terraform.zip"
        - "/var/lib/apt/lists/*"



#echo "===> Clean up..."
#apt-get autoremove --purge -y
#apt-get autoclean -y
##apt-get remove -y --auto-remove
##        build-essential python-pip python-dev git
#
#apt-get clean
#rm -rf /var/lib/apt/lists/*

