#FROM williamyeh/ansible:alpine3
#FROM williamyeh/ansible:alpine3-onbuild
#FROM scottmiller171/ansible-docker-images:ubuntu-14.04
#FROM williamyeh/ansible:ubuntu14.04
FROM williamyeh/ansible:ubuntu14.04-onbuild
